CREATE TYPE [Base].[tv_Credit_Native] AS TABLE (
    [Credit_ID]      INT             IDENTITY (1, 1) NOT NULL,
    [TxSetId]        VARCHAR (22)    NULL,
    [TxSetVrsn]      VARCHAR (1)     NULL,
    [CdtItmId]       VARCHAR (35)    NULL,
    [CdtItmTp]       TINYINT         NULL,
    [[Amt]           NUMERIC (20, 2) NULL,
    [AmtCcy]         NUMERIC (20, 2) NULL,
    [BkCd]           VARCHAR (35)    NULL,
    [AcctNb]         VARCHAR (35)    NULL,
    [RefNb]          VARCHAR (35)    NULL,
    [BnfcryNm]       VARCHAR (70)    NULL,
    [VrtlCdtInd]     BIT             NULL,
    [RefData]        VARCHAR (35)    NULL,
    [BkCdRprdInd]    BIT             NULL,
    [AcctNbRprdInd]  BIT             NULL,
    [AmtRprdInd]     BIT             NULL,
    [SrlNbRprdInd]   BIT             NULL,
    [RefNbRprdInd]   BIT             NULL,
    [BkCdDfltdInd]   BIT             NULL,
    [AcctNbDfltdInd] BIT             NULL,
    [RefNbDfltdInd]  BIT             NULL,
    [sBkCd]          VARCHAR (35)    NULL,
    [sAcctNb]        VARCHAR (35)    NULL,
    [Ccy]            VARCHAR (1)     NULL,
    [Amt_text]       DECIMAL (20, 2) NULL,
    [CrdtItm_Id]     INT             NULL,
    [DbtStopdItm_Id] INT             NULL,
    [DbtItm_Id]      INT             NULL,
    [TxSet_Id]       INT             NULL,
    INDEX [IX_Credit_ID] ([Credit_ID]))
    WITH (MEMORY_OPTIMIZED = ON);

