CREATE TYPE [Base].[tv_Debit_New] AS TABLE (
    [XsdParseId]                    INT             NULL,
    [ItemId]                        BIGINT          NULL,
    [Revision]                      INT             NULL,
    [TXId]                          BIGINT          NULL,
    [SerialNumber]                  INT             NULL,
    [DebitId]                       VARCHAR (25)    NULL,
    [ItemType]                      TINYINT         NULL,
    [Currency]                      TINYINT         NULL,
    [Amount]                        DECIMAL (14, 2) NULL,
    [AccountNumber]                 INT             NULL,
    [Sortcode]                      INT             NULL,
    [TranCode]                      CHAR (2)        NULL,
    [RicherDataRef]                 VARCHAR (256)   NULL,
    [Day1ResponseStartDateTime]     DATETIME2 (7)   NULL,
    [Day1ResponseEndDateTime]       DATETIME2 (7)   NULL,
    [Day2ResponseStartDatetime]     DATETIME2 (7)   NULL,
    [Day2ResponseEndDateTime]       DATETIME2 (7)   NULL,
    [PayReasonCode]                 CHAR (4)        NULL,
    [SettlementPeriodId]            BIGINT          NULL,
    [FraudStatusCode]               CHAR (4)        NULL,
    [FraudReasonCode]               CHAR (4)        NULL,
    [OnUs]                          BIT             NULL,
    [Represent]                     BIT             NULL,
    [HighValue]                     BIT             NULL,
    [PayDecision]                   BIT             NULL,
    [RepairedSortcode]              BIT             NULL,
    [RepairedAccount]               BIT             NULL,
    [RepairedAmount]                BIT             NULL,
    [RepairedSerial]                BIT             NULL,
    [RepairedReference]             BIT             NULL,
    [DefaultedSortcode]             BIT             NULL,
    [DefaultedAccount]              BIT             NULL,
    [DefaultedSerialNumber]         BIT             NULL,
    [Image]                         VARCHAR (MAX)   NULL,
    [ImageHash]                     VARCHAR (128)   NULL,
    [CaptureId]                     VARCHAR (70)    NULL,
    [CaptureDeviceID]               VARCHAR (70)    NULL,
    [CaptureLocation]               VARCHAR (70)    NULL,
    [CaptureDateTime]               DATETIME2 (5)   NULL,
    [FrontImageQuality]             BIT             NULL,
    [RearImageQuality]              BIT             NULL,
    [RiskInd]                       BIT             NULL,
    [DateOfFirstChq]                DATE            NULL,
    [DateOfLastChq]                 DATE            NULL,
    [NbOfCounterparties]            INT             NULL,
    [NbOfGoodCheques]               INT             NULL,
    [NbOfFraudCheques]              INT             NULL,
    [HighestAmt]                    DECIMAL (14, 2) NULL,
    [LargestAmountCurrency]         TINYINT         NULL,
    [RiskIndicator]                 SMALLINT        NULL,
    [SwitchedSortCode]              INT             NULL,
    [SwitchedAccount]               INT             NULL,
    [DuplicateItemId]               VARCHAR (25)    NULL,
    [DuplicateStatus]               VARCHAR (4)     NULL,
    [DateFirstSeen]                 DATE            NULL,
    [OriginalCollectingParticipant] VARCHAR (6)     NULL,
    [OriginalCaptureDate]           DATE            NULL,
    [OriginalSource]                SMALLINT        NULL,
    [StopDate]                      DATE            NULL,
    [StopStatus]                    VARCHAR (4)     NULL,
    [StopAmount]                    DECIMAL (14, 2) NULL,
    [StpAmtCurrency]                TINYINT         NULL,
    [StopBeneficiary]               VARCHAR (50)    NULL,
    [StopStartRange]                INT             NULL,
    [StopEndRange]                  INT             NULL,
    [XMLId]                         INT             NULL,
    [EndPointId]                    VARCHAR (6)     NULL,
    [CollectingParticipantId]       VARCHAR (6)     NOT NULL,
    [TransactionSetId]              VARCHAR (22)    NULL,
    [Version]                       TINYINT         NULL,
    [TSetIDWithVersion]             VARCHAR (24)    NULL,
    [CaptureDate]                   DATETIME2 (7)   NULL,
    [Source]                        SMALLINT        NULL,
    [APGDIN]                        VARCHAR (15)    NULL,
    [APGNoPayReason]                VARCHAR (30)    NULL,
    [OnBank]                        TINYINT         NULL,
    [JGAccount]                     VARCHAR (11)    NULL,
    [IsAmountCorrected]             BIT             NULL,
    [IsAnCorrected]                 BIT             NULL,
    [IsSortCodeCorrected]           BIT             NULL,
    [IsSerialCorrected]             BIT             NULL,
    [DeletedItem]                   BIT             NULL,
    [ItemTypeXML]                   VARCHAR (4)     NULL,
    [CurrencyXML]                   VARCHAR (4)     NULL,
    [StopAmountCurrencyXML]         VARCHAR (10)    NULL,
    [LargestAmountCurrencyXML]      VARCHAR (10)    NULL,
    [RowNumber]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    INDEX [IX_tv_Debit_Reference1] ([ItemId]))
    WITH (MEMORY_OPTIMIZED = ON);

