CREATE TYPE [Base].[tv_Debit_NativeX] AS TABLE (
    [TxSetId]                 VARCHAR (22)    NULL,
    [TxSetVrsn]               VARCHAR (24)    NULL,
    [DbtItmId]                VARCHAR (35)    NULL,
    [DbtItmTp]                TINYINT         NULL,
    [DbtItmTxCd]              VARCHAR (2)     NULL,
    [RpresntdItmInd]          BIT             NULL,
    [Amt]                     NUMERIC (14, 2) NULL,
    [AmtCcy]                  TINYINT         NULL,
    [BkCd]                    INT             NULL,
    [AcctNb]                  INT             NULL,
    [SrlNb]                   INT             NULL,
    [HghValItm]               BIT             NULL,
    [DayOneRspnWndwStartDtTm] DATETIME2 (7)   NULL,
    [DayOneRspnWndwEndDtTm]   DATETIME2 (7)   NULL,
    [DayTwoRspnWndwStartDtTm] DATETIME2 (7)   NULL,
    [DayTwoRspnWndwEndDtTm]   DATETIME2 (7)   NULL,
    [XtrnlDataRef]            VARCHAR (256)   NULL,
    [Img]                     VARCHAR (35)    NULL,
    [FrntImgQltyIndctnInd]    BIT             NULL,
    [BckImgQltyIndctnInd]     BIT             NULL,
    [ChqAtRskInd]             BIT             NULL,
    [DtOfFrstChq]             DATETIME2 (7)   NULL,
    [DtOfLstChq]              DATETIME2 (7)   NULL,
    [NbOfCtrPtys]             INT             NULL,
    [NbOfVldChqs]             INT             NULL,
    [NbOfFrdChqs]             INT             NULL,
    [HghstAmt]                NUMERIC (14, 2) NULL,
    [HghstAmtCcy]             TINYINT         NULL,
    [RskInd]                  INT             NULL,
    [BkCdRprdInd]             BIT             NULL,
    [AcctNbRprdInd]           BIT             NULL,
    [AmtRprdInd]              BIT             NULL,
    [SrlNbRprdInd]            BIT             NULL,
    [RefNbRprdInd]            BIT             NULL,
    [BkCdDfltdInd]            BIT             NULL,
    [AcctNbDfltdInd]          BIT             NULL,
    [SrlNbDfltdInd]           BIT             NULL,
    [sBkCd]                   INT             NULL,
    [sAcctNb]                 INT             NULL,
    [DplctItmId]              VARCHAR (25)    NULL,
    [DbtDplctSts]             VARCHAR (5)     NULL,
    [DtFirstPresntd]          DATETIME2 (7)   NULL,
    [MmbId]                   VARCHAR (6)     NULL,
    [OrgnlCaptrDt]            DATETIME2 (7)   NULL,
    [OrgnlSrc]                INT             NULL,
    [StopdDt]                 DATETIME2 (7)   NULL,
    [StopdSts]                VARCHAR (4)     NULL,
    [StopedAmt]               DECIMAL (14, 2) NULL,
    [StopedAmtCcy]            TINYINT         NULL,
    [BnfcryNm]                VARCHAR (50)    NULL,
    [StopItmStartRg]          INT             NULL,
    [StopItmEndRg]            INT             NULL,
    [DbtItm_Id]               BIGINT          NULL,
    [DbtStopdItm_Id]          INT             NULL,
    [CrdtItm_Id]              INT             NULL,
    [Amt_text]                VARCHAR (255)   NULL,
    [Ccy]                     INT             NULL,
    [DbtItmFrdData_Id]        INT             NULL,
    [HghstAmt_text]           BIGINT          NULL,
    [TxSet_Id]                INT             IDENTITY (1, 1) NOT NULL,
    INDEX [IX_TxSet_Id] ([TxSet_Id]))
    WITH (MEMORY_OPTIMIZED = ON);

