CREATE TYPE [Base].[tv_FinalCredit] AS TABLE (
    [ItemId]                         BIGINT          NULL,
    [CreditId]                       VARCHAR (25)    NOT NULL,
    [ItemUpdateRevision]             INT             NULL,
    [ItemUpdateId]                   BIGINT          NULL,
    [CaptureItemId]                  BIGINT          NULL,
    [EntityId]                       BIGINT          NULL,
    [CollectingParticipantId]        VARCHAR (6)     NULL,
    [AgencyPayingParticipantId]      VARCHAR (6)     NULL,
    [AgencyBeneficiaryParticipantId] VARCHAR (6)     NULL,
    [Reference]                      VARCHAR (18)    NULL,
    [Sortcode]                       INT             NULL,
    [AccountNumber]                  INT             NULL,
    [Amount]                         NUMERIC (20, 2) NULL,
    [Currency]                       TINYINT         NULL,
    [TranCode]                       CHAR (2)        NULL,
    [AlternateSortCode]              INT             NULL,
    [AlternateAccount]               INT             NULL,
    [SwitchedSortCode]               INT             NULL,
    [SwitchedAccount]                INT             NULL,
    [ItemType]                       TINYINT         NULL,
    [DefaultedSortcode]              BIT             NULL,
    [DefaultedAccount]               BIT             NULL,
    [DefaultedReference]             BIT             NULL,
    [OnUs]                           BIT             NULL,
    [RepairedSortcode]               BIT             NULL,
    [RepairedAccount]                BIT             NULL,
    [RepairedAmount]                 BIT             NULL,
    [RepairedSerial]                 BIT             NULL,
    [RepairedReference]              BIT             NULL,
    [InternalTxId]                   BIGINT          NULL,
    [AdjustmentReason]               TINYINT         NULL,
    [NoPayReason]                    VARCHAR (30)    NULL,
    [ReasonCode]                     SMALLINT        NULL,
    [Narrative]                      VARCHAR (255)   NULL,
    [ResponseDate]                   DATE            NULL,
    [ResponseTime]                   TIME (7)        NULL,
    [EISCDPayingParticipantId]       VARCHAR (6)     NULL,
    [EISCDBeneficiaryParticipantId]  VARCHAR (6)     NULL,
    [SettlementParticipantId]        VARCHAR (6)     NULL,
    [ChargingParticipantId]          VARCHAR (6)     NULL,
    [TransactionSetId]               VARCHAR (22)    NULL,
    [Version]                        TINYINT         NULL,
    [cf_OnBank]                      TINYINT         NULL,
    [ICSAmount]                      NUMERIC (20, 2) NULL,
    [TSetIDWithVersion]              VARCHAR (24)    NULL,
    [FinalInclearingState]           SMALLINT        NULL,
    [FinalOutClearingState]          SMALLINT        NULL,
    [FinalclearingState]             SMALLINT        NULL,
    [PostingDate]                    DATE            NULL,
    [ProcessingDate]                 DATE            NULL,
    [CaptureDate]                    DATETIME2 (7)   NULL,
    [ExtractID]                      VARCHAR (26)    NULL,
    [MessageType]                    VARCHAR (10)    NULL,
    [IntMsgType]                     VARCHAR (6)     NULL,
    [Source]                         SMALLINT        NULL,
    [ImageIndicator]                 BIT             NULL,
    [APGDIN]                         VARCHAR (15)    NULL,
    [APGNoPayReason]                 VARCHAR (30)    NULL,
    [JGAccount]                      VARCHAR (11)    NULL,
    [IsAmountCorrected]              BIT             NULL,
    [IsAnCorrected]                  BIT             NULL,
    [IsSortCodeCorrected]            BIT             NULL,
    [IsSerialCorrected]              BIT             NULL,
    [IsRepairedItem]                 BIT             NULL,
    [DeletedItem]                    BIT             NULL,
    [StoppedItem]                    BIT             NULL,
    [FraudResult]                    VARCHAR (15)    NULL,
    [FraudReason]                    VARCHAR (4)     NULL,
    [DuplicateItemIndicator]         VARCHAR (25)    NULL,
    [Day1Date]                       DATE            NULL,
    [IsEntityError]                  BIT             NULL,
    [RowNumber]                      BIGINT          IDENTITY (1, 1) NOT NULL,
    INDEX [IX_tv_FinalCredit_Reference] ([ItemId], [CreditId]))
    WITH (MEMORY_OPTIMIZED = ON);

