CREATE TYPE [Base].[tv_SwitchedItem_native] AS TABLE
(
	BkCd VARCHAR(MAX) NULL
	,AcctNb VARCHAR(MAX) NULL
	,CrdItm_Id BIGINT NULL	
	,INDEX [IXCrdItm_Id] NONCLUSTERED HASH ([CrdItm_Id]) WITH (BUCKET_COUNT = 8) 
)WITH(MEMORY_OPTIMIZED = ON);
GO