CREATE TYPE [Base].[tv_TransitionItems_native] AS TABLE (
    [TransitionItemsSKID]                        BIGINT          NOT NULL,
    [ExtractId]                                  VARCHAR (26)    NULL,
    [UniqueItemIdentifier]                       VARCHAR (25)    NULL,
    [Gender]                                     VARCHAR (3)     NULL,
    [EntityState]                                SMALLINT        NULL,
    [TransactionSetId]                           VARCHAR (22)    NULL,
    [TransactionSetIdWithVersion]                VARCHAR (24)    NULL,
    [TsetEntityState]                            SMALLINT        NULL,
    [IsElectronic]                               BIT             NULL,
    [ItemType]                                   TINYINT         NULL,
    [OnUs]                                       BIT             NULL,
    [cf_OnBank]                                  TINYINT         NULL,
    [cf_DeferredPosting]                         VARCHAR (3)     NULL,
    [cf_NPASortCode]                             VARCHAR (6)     NULL,
    [cf_ChnlInsertReason]                        VARCHAR (20)    NULL,
    [cf_NoPaySuspectRsn]                         VARCHAR (30)    NULL,
    [cf_fCashItem]                               VARCHAR (1)     NULL,
    [HighValue]                                  BIT             NULL,
    [Sortcode]                                   INT             NULL,
    [AccountNumber]                              INT             NULL,
    [SerialReference]                            VARCHAR (18)    NULL,
    [Amount]                                     NUMERIC (20, 2) NULL,
    [Currency]                                   VARCHAR (10)    NULL,
    [TranCode]                                   VARCHAR (2)     NULL,
    [OriginalAmount]                             DECIMAL (11, 2) NULL,
    [ICSAmount]                                  NUMERIC (20, 2) NULL,
    [JGAccount]                                  VARCHAR (11)    NULL,
    [AlternateSortCode]                          INT             NULL,
    [AlternateAccount]                           INT             NULL,
    [SwitchedSortCode]                           INT             NULL,
    [SwitchedAccount]                            INT             NULL,
    [RepresentFlag]                              BIT             NULL,
    [IsSortCodeDefaulted]                        BIT             NULL,
    [ISAccountNumberDefaulted]                   BIT             NULL,
    [ISSerialReferenceDefaulted]                 BIT             NULL,
    [IsSortCodeRepaired]                         BIT             NULL,
    [ISAccountNumberRepaired]                    BIT             NULL,
    [IsAmountRepaired]                           BIT             NULL,
    [ISSerialReferenceRepaired]                  BIT             NULL,
    [IsTCCorrected]                              BIT             NULL,
    [IsANCorrected]                              BIT             NULL,
    [IsSortCodeCorrected]                        BIT             NULL,
    [IsSerialCorrected]                          BIT             NULL,
    [IsReject]                                   BIT             NULL,
    [AdjustmentReason]                           TINYINT         NULL,
    [NoPayReason]                                VARCHAR (30)    NULL,
    [PayDecision]                                BIT             NULL,
    [PayReason]                                  VARCHAR (4)     NULL,
    [Narrative]                                  VARCHAR (255)   NULL,
    [FraudCheckResult]                           VARCHAR (15)    NULL,
    [FraudCheckReason]                           VARCHAR (4)     NULL,
    [Day1ResponseStartDateTime]                  DATETIME2 (3)   NULL,
    [Day1ResponseEndDateTime]                    DATETIME2 (3)   NULL,
    [Day2ResponseWindowStartDateTime]            DATETIME2 (3)   NULL,
    [Day2ResponseWindowEndDateTime]              DATETIME2 (3)   NULL,
    [SettlementPeriodId]                         BIGINT          NULL,
    [CollectingParticipantId]                    VARCHAR (6)     NULL,
    [FrontImageQuality]                          BIT             NULL,
    [RearImageQuality]                           BIT             NULL,
    [ChargingParticipantId]                      VARCHAR (6)     NULL,
    [MessageType]                                VARCHAR (6)     NOT NULL,
    [IntMessageType]                             VARCHAR (6)     NULL,
    [AgencyPayingParticipantId]                  VARCHAR (6)     NULL,
    [AgencyBeneficiaryParticipantId]             VARCHAR (6)     NULL,
    [EISCDPayingParticipantId]                   VARCHAR (6)     NULL,
    [EISCDBeneficiaryParticipantId]              VARCHAR (6)     NULL,
    [SettlementParticipantId]                    VARCHAR (6)     NULL,
    [ItemUpdateId]                               BIGINT          NULL,
    [CaptureItemId]                              BIGINT          NULL,
    [EntityId]                                   BIGINT          NULL,
    [StateRevision]                              INT             NULL,
    [AuditRevision]                              INT             NULL,
    [CoreID]                                     BIGINT          NULL,
    [BeneficiaryName]                            VARCHAR (50)    NULL,
    [TSetSource]                                 SMALLINT        NULL,
    [TSetCaptureDate]                            DATETIME2 (2)   NULL,
    [TSetCollectingLocation]                     VARCHAR (10)    NULL,
    [TSetSubmissionDateTime]                     DATETIME2 (2)   NULL,
    [SwitchRejectionCode]                        VARCHAR (4)     NULL,
    [ChannelRiskType]                            VARCHAR (4)     NULL,
    [DebitReference]                             VARCHAR (18)    NULL,
    [IsAmountCorrected]                          BIT             NULL,
    [DuplicateItemId]                            VARCHAR (25)    NULL,
    [DuplicateItemStatus]                        CHAR (4)        NULL,
    [DuplicateItemDateFirstSeen]                 DATE            NULL,
    [DuplicateItemOriginalCollectingParticipant] VARCHAR (6)     NULL,
    [DuplicateItemOriginalCaptureDate]           DATE            NULL,
    [DuplicateItemOriginalSource]                SMALLINT        NULL,
    [StoppedItemId]                              BIGINT          NULL,
    [StoppedItemStoppedDate]                     DATE            NULL,
    [StoppedItemStatus]                          CHAR (4)        NULL,
    [StoppedItemAmount]                          DECIMAL (14, 2) NULL,
    [StoppedItemBeneficiary]                     VARCHAR (50)    NULL,
    [StoppedItemStopItemStartRange]              INT             NULL,
    [StoppedItemStopItemEndRange]                INT             NULL,
    [cf_ImageDateTime]                           CHAR (28)       NULL,
    INDEX [NCI_TransitionItems_UItemId_TsetIdVrsn] ([UniqueItemIdentifier], [TransactionSetIdWithVersion]))
    WITH (MEMORY_OPTIMIZED = ON);

