CREATE TYPE [Base].[tv_TxSet] AS TABLE (
    [XsdParseId]                  INT           NULL,
    [DocumentId]                  BIGINT        NOT NULL,
    [InternalTXId]                BIGINT        NOT NULL,
    [CollectingPId]               VARCHAR (6)   NOT NULL,
    [TXIdDate]                    DATE          NOT NULL,
    [Source]                      SMALLINT      NOT NULL,
    [Sequence]                    INT           NOT NULL,
    [Version]                     TINYINT       NULL,
    [CollectingParticipantId]     VARCHAR (6)   NOT NULL,
    [CaptureDate]                 DATETIME2 (2) NULL,
    [TSetSubmissionDateTime]      DATETIME2 (2) NULL,
    [AltSource]                   SMALLINT      NOT NULL,
    [NumberOfItems]               INT           NULL,
    [SettlementCode]              TINYINT       NULL,
    [ClearingSystem]              TINYINT       NULL,
    [ClearingSystemMember]        TINYINT       NULL,
    [ClearingSystemMemberId]      INT           NULL,
    [EndPointId]                  VARCHAR (6)   NULL,
    [CollectingBranchLocation]    VARCHAR (8)   NULL,
    [CollectingLocation]          VARCHAR (10)  NULL,
    [ChannelRiskType]             VARCHAR (4)   NULL,
    [ChannelDescription]          VARCHAR (255) NULL,
    [CollectionPoint]             VARCHAR (20)  NULL,
    [CollectionBranchRef]         VARCHAR (255) NULL,
    [FraudCheckOnly]              BIT           NULL,
    [TransactionSetIdWithVersion] VARCHAR (24)  NULL,
    [TransactionSetId]            VARCHAR (22)  NULL,
    INDEX [IX_tv_TxSet_XsdParseId] ([XsdParseId]),
    INDEX [IX_tv_TxSet_Reference] ([InternalTXId]))
    WITH (MEMORY_OPTIMIZED = ON);
GO