CREATE TABLE [Base].[Batch] (
    [BatchId]              BIGINT          NOT NULL,
    [BlockNumber]          SMALLINT        NOT NULL,
    [ImageType]            VARCHAR (7)     NULL,
    [TransactionCode]      CHAR (2)        NULL,
    [AccountNumber]        VARCHAR (13)    NULL,
    [SortCode]             VARCHAR (6)     NULL,
    [Serial]               VARCHAR (20)    NULL,
    [CreditCount]          INT             NULL,
    [DebitCount]           INT             NULL,
    [CreditAmount]         DECIMAL (20, 2) NULL,
    [DebitAmount]          DECIMAL (20, 2) NULL,
    [AcquisitionStartTime] DATETIME2 (2)   NULL,
    [AcquisitionEndTime]   DATETIME2 (2)   NULL,
    [CollectionStartTime]  DATETIME2 (2)   NULL,
    [CollectionEndTime]    DATETIME2 (2)   NULL,
    [RegionId]             CHAR (1)        NULL,
    [ATMId]                VARCHAR (20)    NULL,
    [ATMName]              VARCHAR (40)    NULL,
    [BranchRegionId]       CHAR (1)        NULL,
    [BranchId]             VARCHAR (10)    NULL,
    [BranchName]           VARCHAR (50)    NULL,
    [CorporateId]          VARCHAR (15)    NULL,
    [CorporateName]        VARCHAR (40)    NULL,
    [JobId]                BIGINT          NULL,
    CONSTRAINT [Batch_PrimaryKey] PRIMARY KEY NONCLUSTERED HASH ([BatchId]) WITH (BUCKET_COUNT = 8388608),
    CONSTRAINT [fk_Jobs_Batch] FOREIGN KEY ([JobId]) REFERENCES [Base].[Job] ([JobId]),
    INDEX [NCI_JobId] NONCLUSTERED ([JobId])
)
WITH (MEMORY_OPTIMIZED = ON);

