CREATE TABLE [Base].[Credit] (
    [ItemId]             BIGINT          NOT NULL,
    [Reference]          VARCHAR (18)    NULL,
    [CreditId]           VARCHAR (35)    NOT NULL,
    [InternalTxId]       BIGINT          NULL,
    [Revision]           INT             NULL,
    [ItemType]           TINYINT         NULL,
    [Sortcode]           INT             NULL,
    [AccountNumber]      INT             NULL,
    [Amount]             NUMERIC (20, 2) NULL,
    [Currency]           TINYINT         NULL,
    [ReasonCode]         SMALLINT        NULL,
    [Narrative]          VARCHAR (255)   NULL,
    [TranCode]           CHAR (2)        NULL,
    [DefaultedSortcode]  BIT             NULL,
    [DefaultedAccount]   BIT             NULL,
    [AlternateSortCode]  INT             NULL,
    [AlternateAccount]   INT             NULL,
    [SwitchedSortCode]   INT             NULL,
    [SwitchedAccount]    INT             NULL,
    [RicherDataRef]      VARCHAR (256)   NULL,
    [OnUs]               BIT             NULL,
    [RepairedSortcode]   BIT             NULL,
    [RepairedAccount]    BIT             NULL,
    [RepairedAmount]     BIT             NULL,
    [RepairedSerial]     BIT             NULL,
    [RepairedReference]  BIT             NULL,
    [DefaultedReference] BIT             NULL,
    [TSetID]             VARCHAR (22)    NULL,
    [TSetIDWithVersion]  VARCHAR (24)    NULL,
    CONSTRAINT [Credit_primaryKey] PRIMARY KEY NONCLUSTERED HASH ([ItemId]) WITH (BUCKET_COUNT = 16777216),
    CONSTRAINT [FK_Credit_Currency] FOREIGN KEY ([Currency]) REFERENCES [Lookup].[Currency] ([Id]),
    CONSTRAINT [FK_Credit_ItemType] FOREIGN KEY ([ItemType]) REFERENCES [Lookup].[ItemType] ([Id]),
    INDEX [NCI_ItemId] NONCLUSTERED ([ItemId]),
    INDEX [NCI_InternalTxId] NONCLUSTERED ([InternalTxId]),
    INDEX [NCI_CreditId] NONCLUSTERED ([CreditId]),
    INDEX [NCI_Codeline] NONCLUSTERED ([Sortcode], [AccountNumber], [Reference], [Amount], [ItemId])
)
WITH (MEMORY_OPTIMIZED = ON);

