//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
[System.Xml.Serialization.XmlRootAttribute("Document", Namespace="$(MOMessageNamespace)", IsNullable=false)]
public partial class Document_2 {
    
    private MSG06RequestToPay_2 reqToPayField;
    
    private ICN06MA01 iCNField;
    
    /// <remarks/>
    public MSG06RequestToPay_2 ReqToPay {
        get {
            return this.reqToPayField;
        }
        set {
            this.reqToPayField = value;
        }
    }
    
    /// <remarks/>
    public ICN06MA01 ICN {
        get {
            return this.iCNField;
        }
        set {
            this.iCNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class MSG06RequestToPay_2 {
    
    private MWR000GroupHeader_2 grpHdrField;
    
    private TST000TransactionSet_2[] txSetField;
    
    /// <remarks/>
    public MWR000GroupHeader_2 GrpHdr {
        get {
            return this.grpHdrField;
        }
        set {
            this.grpHdrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TxSet")]
    public TST000TransactionSet_2[] TxSet {
        get {
            return this.txSetField;
        }
        set {
            this.txSetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class MWR000GroupHeader_2 {
    
    private string msgIdField;
    
    private System.DateTime creDtTmField;
    
    private string nbOfTxsField;
    
    private string rcvrIdField;
    
    private MWR070TestIndicator tstIndField;
    
    private byte[] sgntrField;
    
    /// <remarks/>
    public string MsgId {
        get {
            return this.msgIdField;
        }
        set {
            this.msgIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreDtTm {
        get {
            return this.creDtTmField;
        }
        set {
            this.creDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string NbOfTxs {
        get {
            return this.nbOfTxsField;
        }
        set {
            this.nbOfTxsField = value;
        }
    }
    
    /// <remarks/>
    public string RcvrId {
        get {
            return this.rcvrIdField;
        }
        set {
            this.rcvrIdField = value;
        }
    }
    
    /// <remarks/>
    public MWR070TestIndicator TstInd {
        get {
            return this.tstIndField;
        }
        set {
            this.tstIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] Sgntr {
        get {
            return this.sgntrField;
        }
        set {
            this.sgntrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum MWR070TestIndicator {
    
    /// <remarks/>
    @false,
    
    /// <remarks/>
    @true,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class IET000Entity {
    
    private IET010EntityType entityTypeField;
    
    private string entityIdField;
    
    private int stateRevisionField;
    
    private string entityStateField;
    
    private System.DateTime sourceDateTimeField;
    
    /// <remarks/>
    public IET010EntityType EntityType {
        get {
            return this.entityTypeField;
        }
        set {
            this.entityTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string EntityId {
        get {
            return this.entityIdField;
        }
        set {
            this.entityIdField = value;
        }
    }
    
    /// <remarks/>
    public int StateRevision {
        get {
            return this.stateRevisionField;
        }
        set {
            this.stateRevisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string EntityState {
        get {
            return this.entityStateField;
        }
        set {
            this.entityStateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime SourceDateTime {
        get {
            return this.sourceDateTimeField;
        }
        set {
            this.sourceDateTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum IET010EntityType {
    
    /// <remarks/>
    T,
    
    /// <remarks/>
    I,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class ICN000Core {
    
    private System.DateTime businessDateField;
    
    private string extractIdField;
    
    private string processingParticipantIdField;
    
    private ICN050ExtMessageType extMessageTypeField;
    
    private ICN060IntMessageType intMessageTypeField;
    
    private ICN070MessageSource messageSourceField;
    
    private ICN080MessageDestination messageDestinationField;
    
    private int recordCountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime BusinessDate {
        get {
            return this.businessDateField;
        }
        set {
            this.businessDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ExtractId {
        get {
            return this.extractIdField;
        }
        set {
            this.extractIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ProcessingParticipantId {
        get {
            return this.processingParticipantIdField;
        }
        set {
            this.processingParticipantIdField = value;
        }
    }
    
    /// <remarks/>
    public ICN050ExtMessageType ExtMessageType {
        get {
            return this.extMessageTypeField;
        }
        set {
            this.extMessageTypeField = value;
        }
    }
    
    /// <remarks/>
    public ICN060IntMessageType IntMessageType {
        get {
            return this.intMessageTypeField;
        }
        set {
            this.intMessageTypeField = value;
        }
    }
    
    /// <remarks/>
    public ICN070MessageSource MessageSource {
        get {
            return this.messageSourceField;
        }
        set {
            this.messageSourceField = value;
        }
    }
    
    /// <remarks/>
    public ICN080MessageDestination MessageDestination {
        get {
            return this.messageDestinationField;
        }
        set {
            this.messageDestinationField = value;
        }
    }
    
    /// <remarks/>
    public int RecordCounts {
        get {
            return this.recordCountsField;
        }
        set {
            this.recordCountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum ICN050ExtMessageType {
    
    /// <remarks/>
    MSG06,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum ICN060IntMessageType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("06MA01")]
    Item06MA01,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum ICN070MessageSource {
    
    /// <remarks/>
    MO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum ICN080MessageDestination {
    
    /// <remarks/>
    IA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class ICN06MA01 {
    
    private ICN000Core coreField;
    
    private IET000Entity[] entitiesField;
    
    /// <remarks/>
    public ICN000Core Core {
        get {
            return this.coreField;
        }
        set {
            this.coreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
    public IET000Entity[] Entities {
        get {
            return this.entitiesField;
        }
        set {
            this.entitiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DSI030StopAmount {
    
    private ActiveCurrencyCode ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActiveCurrencyCode Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum ActiveCurrencyCode {
    
    /// <remarks/>
    GBP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DSI000DebitStoppedItem {
    
    private System.DateTime stopdDtField;
    
    private DSI020StopStatus stopdStsField;
    
    private DSI030StopAmount amtField;
    
    private string bnfcryNmField;
    
    private string stopItmStartRgField;
    
    private string stopItmEndRgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime StopdDt {
        get {
            return this.stopdDtField;
        }
        set {
            this.stopdDtField = value;
        }
    }
    
    /// <remarks/>
    public DSI020StopStatus StopdSts {
        get {
            return this.stopdStsField;
        }
        set {
            this.stopdStsField = value;
        }
    }
    
    /// <remarks/>
    public DSI030StopAmount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public string BnfcryNm {
        get {
            return this.bnfcryNmField;
        }
        set {
            this.bnfcryNmField = value;
        }
    }
    
    /// <remarks/>
    public string StopItmStartRg {
        get {
            return this.stopItmStartRgField;
        }
        set {
            this.stopItmStartRgField = value;
        }
    }
    
    /// <remarks/>
    public string StopItmEndRg {
        get {
            return this.stopItmEndRgField;
        }
        set {
            this.stopItmEndRgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum DSI020StopStatus {
    
    /// <remarks/>
    FULL,
    
    /// <remarks/>
    PARA,
    
    /// <remarks/>
    PARS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DDI000DebitDuplicateItem {
    
    private string dplctItmIdField;
    
    private DDI010DuplicateStatus dbtDplctStsField;
    
    private System.DateTime dtFirstPresntdField;
    
    private string mmbIdField;
    
    private System.DateTime orgnlCaptrDtField;
    
    private bool orgnlCaptrDtFieldSpecified;
    
    private string orgnlSrcField;
    
    /// <remarks/>
    public string DplctItmId {
        get {
            return this.dplctItmIdField;
        }
        set {
            this.dplctItmIdField = value;
        }
    }
    
    /// <remarks/>
    public DDI010DuplicateStatus DbtDplctSts {
        get {
            return this.dbtDplctStsField;
        }
        set {
            this.dbtDplctStsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DtFirstPresntd {
        get {
            return this.dtFirstPresntdField;
        }
        set {
            this.dtFirstPresntdField = value;
        }
    }
    
    /// <remarks/>
    public string MmbId {
        get {
            return this.mmbIdField;
        }
        set {
            this.mmbIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime OrgnlCaptrDt {
        get {
            return this.orgnlCaptrDtField;
        }
        set {
            this.orgnlCaptrDtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OrgnlCaptrDtSpecified {
        get {
            return this.orgnlCaptrDtFieldSpecified;
        }
        set {
            this.orgnlCaptrDtFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string OrgnlSrc {
        get {
            return this.orgnlSrcField;
        }
        set {
            this.orgnlSrcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum DDI010DuplicateStatus {
    
    /// <remarks/>
    FULL,
    
    /// <remarks/>
    PART,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DIT000DefaultedItem_3 {
    
    private bool bkCdDfltdIndField;
    
    private bool acctNbDfltdIndField;
    
    private bool srlNbDfltdIndField;
    
    private bool srlNbDfltdIndFieldSpecified;
    
    /// <remarks/>
    public bool BkCdDfltdInd {
        get {
            return this.bkCdDfltdIndField;
        }
        set {
            this.bkCdDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool AcctNbDfltdInd {
        get {
            return this.acctNbDfltdIndField;
        }
        set {
            this.acctNbDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool SrlNbDfltdInd {
        get {
            return this.srlNbDfltdIndField;
        }
        set {
            this.srlNbDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SrlNbDfltdIndSpecified {
        get {
            return this.srlNbDfltdIndFieldSpecified;
        }
        set {
            this.srlNbDfltdIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DBF070HighestAmount {
    
    private ActiveCurrencyCode ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActiveCurrencyCode Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DBF000DebitItemFraudData {
    
    private bool chqAtRskIndField;
    
    private bool chqAtRskIndFieldSpecified;
    
    private System.DateTime dtOfFrstChqField;
    
    private bool dtOfFrstChqFieldSpecified;
    
    private System.DateTime dtOfLstChqField;
    
    private bool dtOfLstChqFieldSpecified;
    
    private string nbOfCtrPtysField;
    
    private string nbOfVldChqsField;
    
    private string nbOfFrdChqsField;
    
    private DBF070HighestAmount hghstAmtField;
    
    private string rskIndField;
    
    /// <remarks/>
    public bool ChqAtRskInd {
        get {
            return this.chqAtRskIndField;
        }
        set {
            this.chqAtRskIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ChqAtRskIndSpecified {
        get {
            return this.chqAtRskIndFieldSpecified;
        }
        set {
            this.chqAtRskIndFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DtOfFrstChq {
        get {
            return this.dtOfFrstChqField;
        }
        set {
            this.dtOfFrstChqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtOfFrstChqSpecified {
        get {
            return this.dtOfFrstChqFieldSpecified;
        }
        set {
            this.dtOfFrstChqFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DtOfLstChq {
        get {
            return this.dtOfLstChqField;
        }
        set {
            this.dtOfLstChqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DtOfLstChqSpecified {
        get {
            return this.dtOfLstChqFieldSpecified;
        }
        set {
            this.dtOfLstChqFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string NbOfCtrPtys {
        get {
            return this.nbOfCtrPtysField;
        }
        set {
            this.nbOfCtrPtysField = value;
        }
    }
    
    /// <remarks/>
    public string NbOfVldChqs {
        get {
            return this.nbOfVldChqsField;
        }
        set {
            this.nbOfVldChqsField = value;
        }
    }
    
    /// <remarks/>
    public string NbOfFrdChqs {
        get {
            return this.nbOfFrdChqsField;
        }
        set {
            this.nbOfFrdChqsField = value;
        }
    }
    
    /// <remarks/>
    public DBF070HighestAmount HghstAmt {
        get {
            return this.hghstAmtField;
        }
        set {
            this.hghstAmtField = value;
        }
    }
    
    /// <remarks/>
    public string RskInd {
        get {
            return this.rskIndField;
        }
        set {
            this.rskIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class ITI000ItemImageData_2 {
    
    private string imgField;
    
    private bool frntImgQltyIndctnIndField;
    
    private bool bckImgQltyIndctnIndField;
    
    /// <remarks/>
    public string Img {
        get {
            return this.imgField;
        }
        set {
            this.imgField = value;
        }
    }
    
    /// <remarks/>
    public bool FrntImgQltyIndctnInd {
        get {
            return this.frntImgQltyIndctnIndField;
        }
        set {
            this.frntImgQltyIndctnIndField = value;
        }
    }
    
    /// <remarks/>
    public bool BckImgQltyIndctnInd {
        get {
            return this.bckImgQltyIndctnIndField;
        }
        set {
            this.bckImgQltyIndctnIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DBI060Amount {
    
    private ActiveCurrencyCode ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActiveCurrencyCode Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DBI000DebitItem_2 {
    
    private string dbtItmIdField;
    
    private DBI020DebitItemType dbtItmTpField;
    
    private string dbtItmTxCdField;
    
    private bool rpresntdItmIndField;
    
    private DBI060Amount amtField;
    
    private string bkCdField;
    
    private string acctNbField;
    
    private string srlNbField;
    
    private bool hghValItmField;
    
    private System.DateTime dayOneRspnWndwStartDtTmField;
    
    private bool dayOneRspnWndwStartDtTmFieldSpecified;
    
    private System.DateTime dayOneRspnWndwEndDtTmField;
    
    private bool dayOneRspnWndwEndDtTmFieldSpecified;
    
    private System.DateTime dayTwoRspnWndwStartDtTmField;
    
    private System.DateTime dayTwoRspnWndwEndDtTmField;
    
    private string xtrnlDataRefField;
    
    private ITI000ItemImageData_2 itmImgDataField;
    
    private DBF000DebitItemFraudData dbtItmFrdDataField;
    
    private RIT000RepairedItem_2 rprdItmField;
    
    private DIT000DefaultedItem_3 dfltdItmField;
    
    private SWI000SwitchedItem swtchdItmField;
    
    private DDI000DebitDuplicateItem dbtDplctItmField;
    
    private DSI000DebitStoppedItem dbtStopdItmField;
    
    /// <remarks/>
    public string DbtItmId {
        get {
            return this.dbtItmIdField;
        }
        set {
            this.dbtItmIdField = value;
        }
    }
    
    /// <remarks/>
    public DBI020DebitItemType DbtItmTp {
        get {
            return this.dbtItmTpField;
        }
        set {
            this.dbtItmTpField = value;
        }
    }
    
    /// <remarks/>
    public string DbtItmTxCd {
        get {
            return this.dbtItmTxCdField;
        }
        set {
            this.dbtItmTxCdField = value;
        }
    }
    
    /// <remarks/>
    public bool RpresntdItmInd {
        get {
            return this.rpresntdItmIndField;
        }
        set {
            this.rpresntdItmIndField = value;
        }
    }
    
    /// <remarks/>
    public DBI060Amount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public string BkCd {
        get {
            return this.bkCdField;
        }
        set {
            this.bkCdField = value;
        }
    }
    
    /// <remarks/>
    public string AcctNb {
        get {
            return this.acctNbField;
        }
        set {
            this.acctNbField = value;
        }
    }
    
    /// <remarks/>
    public string SrlNb {
        get {
            return this.srlNbField;
        }
        set {
            this.srlNbField = value;
        }
    }
    
    /// <remarks/>
    public bool HghValItm {
        get {
            return this.hghValItmField;
        }
        set {
            this.hghValItmField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DayOneRspnWndwStartDtTm {
        get {
            return this.dayOneRspnWndwStartDtTmField;
        }
        set {
            this.dayOneRspnWndwStartDtTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DayOneRspnWndwStartDtTmSpecified {
        get {
            return this.dayOneRspnWndwStartDtTmFieldSpecified;
        }
        set {
            this.dayOneRspnWndwStartDtTmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DayOneRspnWndwEndDtTm {
        get {
            return this.dayOneRspnWndwEndDtTmField;
        }
        set {
            this.dayOneRspnWndwEndDtTmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DayOneRspnWndwEndDtTmSpecified {
        get {
            return this.dayOneRspnWndwEndDtTmFieldSpecified;
        }
        set {
            this.dayOneRspnWndwEndDtTmFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DayTwoRspnWndwStartDtTm {
        get {
            return this.dayTwoRspnWndwStartDtTmField;
        }
        set {
            this.dayTwoRspnWndwStartDtTmField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DayTwoRspnWndwEndDtTm {
        get {
            return this.dayTwoRspnWndwEndDtTmField;
        }
        set {
            this.dayTwoRspnWndwEndDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string XtrnlDataRef {
        get {
            return this.xtrnlDataRefField;
        }
        set {
            this.xtrnlDataRefField = value;
        }
    }
    
    /// <remarks/>
    public ITI000ItemImageData_2 ItmImgData {
        get {
            return this.itmImgDataField;
        }
        set {
            this.itmImgDataField = value;
        }
    }
    
    /// <remarks/>
    public DBF000DebitItemFraudData DbtItmFrdData {
        get {
            return this.dbtItmFrdDataField;
        }
        set {
            this.dbtItmFrdDataField = value;
        }
    }
    
    /// <remarks/>
    public RIT000RepairedItem_2 RprdItm {
        get {
            return this.rprdItmField;
        }
        set {
            this.rprdItmField = value;
        }
    }
    
    /// <remarks/>
    public DIT000DefaultedItem_3 DfltdItm {
        get {
            return this.dfltdItmField;
        }
        set {
            this.dfltdItmField = value;
        }
    }
    
    /// <remarks/>
    public SWI000SwitchedItem SwtchdItm {
        get {
            return this.swtchdItmField;
        }
        set {
            this.swtchdItmField = value;
        }
    }
    
    /// <remarks/>
    public DDI000DebitDuplicateItem DbtDplctItm {
        get {
            return this.dbtDplctItmField;
        }
        set {
            this.dbtDplctItmField = value;
        }
    }
    
    /// <remarks/>
    public DSI000DebitStoppedItem DbtStopdItm {
        get {
            return this.dbtStopdItmField;
        }
        set {
            this.dbtStopdItmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum DBI020DebitItemType {
    
    /// <remarks/>
    IODI,
    
    /// <remarks/>
    ITPI,
    
    /// <remarks/>
    RTPI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class RIT000RepairedItem_2 {
    
    private bool bkCdRprdIndField;
    
    private bool acctNbRprdIndField;
    
    private bool amtRprdIndField;
    
    private bool srlNbRprdIndField;
    
    private bool refNbRprdIndField;
    
    /// <remarks/>
    public bool BkCdRprdInd {
        get {
            return this.bkCdRprdIndField;
        }
        set {
            this.bkCdRprdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool AcctNbRprdInd {
        get {
            return this.acctNbRprdIndField;
        }
        set {
            this.acctNbRprdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool AmtRprdInd {
        get {
            return this.amtRprdIndField;
        }
        set {
            this.amtRprdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool SrlNbRprdInd {
        get {
            return this.srlNbRprdIndField;
        }
        set {
            this.srlNbRprdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool RefNbRprdInd {
        get {
            return this.refNbRprdIndField;
        }
        set {
            this.refNbRprdIndField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class SWI000SwitchedItem {
    
    private string bkCdField;
    
    private string acctNbField;
    
    /// <remarks/>
    public string BkCd {
        get {
            return this.bkCdField;
        }
        set {
            this.bkCdField = value;
        }
    }
    
    /// <remarks/>
    public string AcctNb {
        get {
            return this.acctNbField;
        }
        set {
            this.acctNbField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class DIT000DefaultedItem_2 {
    
    private bool bkCdDfltdIndField;
    
    private bool acctNbDfltdIndField;
    
    private bool refNbDfltdIndField;
    
    private bool refNbDfltdIndFieldSpecified;
    
    /// <remarks/>
    public bool BkCdDfltdInd {
        get {
            return this.bkCdDfltdIndField;
        }
        set {
            this.bkCdDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool AcctNbDfltdInd {
        get {
            return this.acctNbDfltdIndField;
        }
        set {
            this.acctNbDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    public bool RefNbDfltdInd {
        get {
            return this.refNbDfltdIndField;
        }
        set {
            this.refNbDfltdIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RefNbDfltdIndSpecified {
        get {
            return this.refNbDfltdIndFieldSpecified;
        }
        set {
            this.refNbDfltdIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class CRF000CreditItemFraudData {
    
    private string bnfcryNmField;
    
    private bool vrtlCdtIndField;
    
    private string refDataField;
    
    /// <remarks/>
    public string BnfcryNm {
        get {
            return this.bnfcryNmField;
        }
        set {
            this.bnfcryNmField = value;
        }
    }
    
    /// <remarks/>
    public bool VrtlCdtInd {
        get {
            return this.vrtlCdtIndField;
        }
        set {
            this.vrtlCdtIndField = value;
        }
    }
    
    /// <remarks/>
    public string RefData {
        get {
            return this.refDataField;
        }
        set {
            this.refDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class CRI050Amount {
    
    private ActiveCurrencyCode ccyField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActiveCurrencyCode Ccy {
        get {
            return this.ccyField;
        }
        set {
            this.ccyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class CRI000CreditItem_2 {
    
    private string cdtItmIdField;
    
    private CRI020CreditItemType cdtItmTpField;
    
    private CRI050Amount amtField;
    
    private string bkCdField;
    
    private string acctNbField;
    
    private string refNbField;
    
    private CRF000CreditItemFraudData cdtItmFrdDataField;
    
    private RIT000RepairedItem_2 rprdItmField;
    
    private DIT000DefaultedItem_2 dfltdItmField;
    
    private SWI000SwitchedItem swtchdItmField;
    
    /// <remarks/>
    public string CdtItmId {
        get {
            return this.cdtItmIdField;
        }
        set {
            this.cdtItmIdField = value;
        }
    }
    
    /// <remarks/>
    public CRI020CreditItemType CdtItmTp {
        get {
            return this.cdtItmTpField;
        }
        set {
            this.cdtItmTpField = value;
        }
    }
    
    /// <remarks/>
    public CRI050Amount Amt {
        get {
            return this.amtField;
        }
        set {
            this.amtField = value;
        }
    }
    
    /// <remarks/>
    public string BkCd {
        get {
            return this.bkCdField;
        }
        set {
            this.bkCdField = value;
        }
    }
    
    /// <remarks/>
    public string AcctNb {
        get {
            return this.acctNbField;
        }
        set {
            this.acctNbField = value;
        }
    }
    
    /// <remarks/>
    public string RefNb {
        get {
            return this.refNbField;
        }
        set {
            this.refNbField = value;
        }
    }
    
    /// <remarks/>
    public CRF000CreditItemFraudData CdtItmFrdData {
        get {
            return this.cdtItmFrdDataField;
        }
        set {
            this.cdtItmFrdDataField = value;
        }
    }
    
    /// <remarks/>
    public RIT000RepairedItem_2 RprdItm {
        get {
            return this.rprdItmField;
        }
        set {
            this.rprdItmField = value;
        }
    }
    
    /// <remarks/>
    public DIT000DefaultedItem_2 DfltdItm {
        get {
            return this.dfltdItmField;
        }
        set {
            this.dfltdItmField = value;
        }
    }
    
    /// <remarks/>
    public SWI000SwitchedItem SwtchdItm {
        get {
            return this.swtchdItmField;
        }
        set {
            this.swtchdItmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public enum CRI020CreditItemType {
    
    /// <remarks/>
    CRDI,
    
    /// <remarks/>
    IOCI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="$(MOMessageNamespace)")]
public partial class TST000TransactionSet_2 {
    
    private string txSetIdField;
    
    private string txSetVrsnField;
    
    private string colltngPtcptIdField;
    
    private System.DateTime captrdDtTmField;
    
    private System.DateTime txSetSubDtTmField;
    
    private string srcField;
    
    private string colltngBrnchLctnField;
    
    private string colltngLctnField;
    
    private string chanlRskTpField;
    
    private string chanlDescField;
    
    private string colltnPtField;
    
    private string colltngBrnchRefField;
    
    private string nbOfItmsField;
    
    private string endPtIdField;
    
    private CRI000CreditItem_2[] crdtItmField;
    
    private DBI000DebitItem_2 dbtItmField;
    
    /// <remarks/>
    public string TxSetId {
        get {
            return this.txSetIdField;
        }
        set {
            this.txSetIdField = value;
        }
    }
    
    /// <remarks/>
    public string TxSetVrsn {
        get {
            return this.txSetVrsnField;
        }
        set {
            this.txSetVrsnField = value;
        }
    }
    
    /// <remarks/>
    public string ColltngPtcptId {
        get {
            return this.colltngPtcptIdField;
        }
        set {
            this.colltngPtcptIdField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CaptrdDtTm {
        get {
            return this.captrdDtTmField;
        }
        set {
            this.captrdDtTmField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TxSetSubDtTm {
        get {
            return this.txSetSubDtTmField;
        }
        set {
            this.txSetSubDtTmField = value;
        }
    }
    
    /// <remarks/>
    public string Src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
    
    /// <remarks/>
    public string ColltngBrnchLctn {
        get {
            return this.colltngBrnchLctnField;
        }
        set {
            this.colltngBrnchLctnField = value;
        }
    }
    
    /// <remarks/>
    public string ColltngLctn {
        get {
            return this.colltngLctnField;
        }
        set {
            this.colltngLctnField = value;
        }
    }
    
    /// <remarks/>
    public string ChanlRskTp {
        get {
            return this.chanlRskTpField;
        }
        set {
            this.chanlRskTpField = value;
        }
    }
    
    /// <remarks/>
    public string ChanlDesc {
        get {
            return this.chanlDescField;
        }
        set {
            this.chanlDescField = value;
        }
    }
    
    /// <remarks/>
    public string ColltnPt {
        get {
            return this.colltnPtField;
        }
        set {
            this.colltnPtField = value;
        }
    }
    
    /// <remarks/>
    public string ColltngBrnchRef {
        get {
            return this.colltngBrnchRefField;
        }
        set {
            this.colltngBrnchRefField = value;
        }
    }
    
    /// <remarks/>
    public string NbOfItms {
        get {
            return this.nbOfItmsField;
        }
        set {
            this.nbOfItmsField = value;
        }
    }
    
    /// <remarks/>
    public string EndPtId {
        get {
            return this.endPtIdField;
        }
        set {
            this.endPtIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CrdtItm")]
    public CRI000CreditItem_2[] CrdtItm {
        get {
            return this.crdtItmField;
        }
        set {
            this.crdtItmField = value;
        }
    }
    
    /// <remarks/>
    public DBI000DebitItem_2 DbtItm {
        get {
            return this.dbtItmField;
        }
        set {
            this.dbtItmField = value;
        }
    }
}
